blueprint:
  name: Unlock Door Before Event with Keyword
  description: >
    Unlocks a door a specified amount of time before an event starts if the event’s title contains a specified keyword.
  domain: automation
  input:
    calendar_entity:
      name: Calendar Entity
      description: Select the calendar to monitor for events.
      selector:
        entity:
          domain: calendar
    door_keyword:
      name: Door Keyword
      description: The keyword that must appear in the event title for unlocking to occur.
      default: "*"
      selector:
        text: {}
    unlock_offset:
      name: Unlock Offset
      description: The time before an event's start when the door should be unlocked.
      default: "-00:30:00"
      selector:
        time: {}
    door_lock_entity:
      name: Door Lock Entity
      description: The door lock to check. The automation will only unlock if this door is currently locked.
      selector:
        entity:
          domain: lock
    door_lock_rule_select:
      name: Door Lock Rule Select Entity
      description: The select entity that controls the door lock mode.
      selector:
        entity:
          domain: select
    notify_service:
      name: Notification Service
      description: The notification service to use.
      default: "notify.mobile_app_jt_iphone_16"
      selector:
        text: {}
  trigger:
    - platform: calendar
      event: start
      entity_id: !input calendar_entity
      offset: !input unlock_offset
  condition:
    - condition: state
      entity_id: !input door_lock_entity
      state: "locked"
    - condition: template
      value_template: >
        {% set summary = trigger.calendar_event.summary | lower %}
        {{ summary.find((!input door_keyword) | lower) != -1 and 'canceled' not in summary }}
  action:
    - service: select.select_option
      target:
        entity_id: !input door_lock_rule_select
      data:
        option: "keep_unlock"
    - service: !input notify_service
      data:
        title: "Door Unlocked"
        message: >
          Event starting soon. Door unlocked {{ !input unlock_offset }} before event.
  mode: single
