blueprint:
  name: Lock Door via Reset Select (Fixed Syntax)
  description: >
    Triggers a 'Reset' on a select entity a specified duration after a calendar event ends.
    Checks for overlaps (calendar must be 'off') and keyword matches.
    Notification confirms the event ended and doors are locked.
  domain: automation
  input:
    calendar_entity:
      name: Calendar Entity
      description: The calendar to monitor.
      selector:
        entity:
          domain: calendar
    lock_offset:
      name: Lock Offset
      description: How long to wait after the event ends before triggering the reset.
      default: "0:15:0"
      selector:
        duration: {}
    input_text_keyword:
      name: Keyword Input Text
      description: >
        Entity containing the keyword. 
        If set, automation ONLY runs if the Event Title or Description contains this text.
        If empty, runs for every event.
      selector:
        entity:
          domain: input_text
    door_lock_entity:
      name: Door Lock Check
      description: The door lock to check (automation only runs if this is currently unlocked).
      selector:
        entity:
          domain: lock
    door_lock_rule_select:
      name: Door Lock Rule Select Entity
      description: The select entity that triggers your locking logic (sets to 'reset').
      selector:
        entity:
          domain: select
    notify_device:
      name: Notification Device
      description: Select the mobile device to send notifications to.
      selector:
        device:
          integration: mobile_app

# ----------------------------------------------------------------------
# VARIABLES SECTION
# This maps the YAML !input to a variable that Jinja templates can read
# ----------------------------------------------------------------------
variables:
  keyword_entity_id: !input input_text_keyword

trigger:
  - platform: calendar
    event: end
    entity_id: !input calendar_entity
    offset: !input lock_offset

condition:
  # 1. Check if door is unlocked
  - condition: state
    entity_id: !input door_lock_entity
    state: "unlocked"

  # 2. Check for Overlaps (Calendar must be 'off' / free)
  - condition: state
    entity_id: !input calendar_entity
    state: "off"

  # 3. Keyword Check (Title or Description)
  # Now using the 'keyword_entity_id' variable defined above
  - condition: template
    value_template: >
      {% set keyword = states(keyword_entity_id) %}
      {% set title = trigger.calendar_event.summary | default('') %}
      {% set desc = trigger.calendar_event.description | default('') %}
      {{ keyword == '' or keyword in title or keyword in desc }}

action:
  - service: select.select_option
    target:
      entity_id: !input door_lock_rule_select
    data:
      option: "reset"
  
  - domain: mobile_app
    type: notify
    device_id: !input notify_device
    title: "Doors Locked"
    message: "The event '{{ trigger.calendar_event.summary }}' has finished and the doors have locked."

mode: single
