blueprint:
  name: "Safety: Periodic Sweep (With Grace Period)"
  description: >
    The "Janitor" for your locks. Runs every 15 minutes.
    
    SMART LOGIC:
    1. Fetches a LIST of all recent events.
    2. Checks if an event is active OR if we are still in the "Grace Period" after an event.
    3. If yes, it does nothing (Door stays open).
    4. If no valid events (and grace period has passed), it LOCKS the door.
  domain: automation
  input:
    calendar_entity:
      name: Calendar Entity
      selector:
        entity:
          domain: calendar
    door_lock_entity:
      name: Door Lock Entity
      selector:
        entity:
          domain: lock
    door_lock_rule_select:
      name: Door Lock Rule Select Entity
      selector:
        entity:
          domain: select
    notify_device:
      name: Notification Device
      selector:
        device:
          integration: mobile_app
    # --- NEW INPUT ---
    post_event_buffer:
      name: Grace Period (Minutes)
      description: "How many minutes to wait after a meeting ends before forcing a lock? Set this slightly HIGHER than your standard unlock offset."
      default: 35
      selector:
        number:
          min: 0
          max: 120
          unit_of_measurement: minutes

variables:
  calendar_id: !input calendar_entity
  # Pass the input to a variable so the template can use it
  buffer_minutes: !input post_event_buffer

trigger:
  - platform: time_pattern
    minutes: "/15"

condition:
  - condition: state
    entity_id: !input door_lock_entity
    state: "unlocked"

action:
  - service: calendar.get_events
    target:
      entity_id: !input calendar_entity
    data:
      # We look back slightly to catch events that just ended
      start_date_time: "{{ now() - timedelta(hours=1) }}" 
      end_date_time: "{{ now() + timedelta(minutes=5) }}"
    response_variable: scheduled_events

  - choose:
      - conditions:
          - condition: template
            value_template: >
              {% set events = scheduled_events[calendar_id]['events'] %}
              {% set ns = namespace(found=false) %}
              
              {# Convert input variable to integer #}
              {% set buffer = buffer_minutes | int %}

              {% for event in events %}
                {% set start = as_datetime(event.start) %}
                {% set end = as_datetime(event.end) %}
                
                {# CALCULATE THE BUFFERED END TIME #}
                {% set end_with_buffer = end + timedelta(minutes=buffer) %}

                {# Logic: Is it active now OR are we inside the buffer window? #}
                {% if start <= now() <= end_with_buffer %}
                  
                  {% set title = event.summary | lower %}
                  {% if 'canceled' not in title and 'cancelled' not in title %}
                     {% set ns.found = true %}
                  {% endif %}
                  
                {% endif %}
              {% endfor %}
              
              {# If found is FALSE, it means we are past the meeting AND past the buffer #}
              {{ ns.found == false }}
        sequence:
          - service: select.select_option
            target:
              entity_id: !input door_lock_rule_select
            data:
              option: "reset"
          - domain: mobile_app
            type: notify
            device_id: !input notify_device
            title: "Security Sweeper"
            message: "Grace period ended. No active events. Locking door."
