blueprint:
  name: "Safety: Emergency Lockdown & Recovery"
  description: >
    Manages the full Emergency Cycle (Disable & Restore).
    
    1. EMERGENCY LOCKDOWN (Disable):
       - Trigger: Unifi Sensor detects Lockdown.
       - Action: Turns OFF the selected automations (Unlocker, Locker, etc).
       - Action: Sends "Lockdown Active" alert.
       
    2. SYSTEM RECOVERY (Restore):
       - Trigger: Manual press of 'Reset Button' (Helper).
       - Action: Turns ON the selected automations.
       - Action: Sends "System Restored" alert.
  domain: automation
  input:
    unifi_lockdown_sensor:
      name: Unifi Lockdown Sensor
      description: >
        The sensor from Unifi Access that turns 'on' during a lockdown.
      selector:
        entity:
          domain: binary_sensor
    manual_reset_button:
      name: Manual Reset Button
      description: >
        The Helper Button used to signal "All Clear".
      selector:
        entity:
          domain: input_button
    automations_to_manage:
      name: Automations to Manage
      description: >
        Select ALL automations to Disable during emergency and Enable during recovery.
        (e.g. Unlock Scheduler, Lock Scheduler, Sweeper).
      selector:
        entity:
          domain: automation
          multiple: true
    notify_device:
      name: Notification Device
      selector:
        device:
          integration: mobile_app

trigger:
  # Trigger 1: Emergency Starts
  - platform: state
    entity_id: !input unifi_lockdown_sensor
    to: "on"
    id: "lockdown_start"

  # Trigger 2: Manual Recovery
  - platform: state
    entity_id: !input manual_reset_button
    id: "manual_reset"

action:
  - choose:
      # SCENARIO A: LOCKDOWN (DISABLE)
      - conditions:
          - condition: trigger
            id: "lockdown_start"
        sequence:
          # 1. Kill the Schedulers
          - service: automation.turn_off
            target:
              entity_id: !input automations_to_manage
          # 2. Notify
          - domain: mobile_app
            type: notify
            device_id: !input notify_device
            title: "⚠️ LOCKDOWN DETECTED"
            message: "Emergency Mode Active. All schedules DISABLED."

      # SCENARIO B: RECOVERY (ENABLE)
      - conditions:
          - condition: trigger
            id: "manual_reset"
        sequence:
          # 1. Revive the Schedulers
          - service: automation.turn_on
            target:
              entity_id: !input automations_to_manage
          # 2. Notify
          - domain: mobile_app
            type: notify
            device_id: !input notify_device
            title: "System Restored"
            message: "All Clear. Schedules have been RE-ENABLED."
