blueprint:
  name: "Safety: Lockdown & Recovery (Text Trigger)"
  description: >
    Manages the full Emergency Cycle (Disable & Restore).
    
    1. EMERGENCY LOCKDOWN (Disable):
       - Trigger: When your Unifi Rule changes to "Keep it locked" (or any text you choose).
       - Action: Turns OFF the selected automations (Unlocker, Locker, etc).
       - Action: Sends "Lockdown Active" alert.
       
    2. SYSTEM RECOVERY (Restore):
       - Trigger: Manual press of 'Schedule Reactivate' Button (Helper).
       - Action: Turns ON the selected automations.
       - Action: Sends "System Restored" alert.
  domain: automation
  input:
    lockdown_trigger_entity:
      name: Lockdown Trigger Entity
      description: "The Unifi entity that changes during lockdown (e.g., select.door_lock_rule)."
      selector:
        entity:
    lockdown_trigger_value:
      name: Lockdown State Text
      description: "The exact text that indicates a lockdown (e.g., keep_lock)."
      default: "keep_lock"
      selector:
        text: {}
    manual_reset_button:
      name: Manual Reset Button
      description: "The Button Helper (e.g., Schedule Reactivate) to restore the system."
      selector:
        entity:
          domain: input_button
    automations_to_manage:
      name: Automations to Manage
      description: "Select ALL automations to Disable during emergency and Enable during recovery."
      selector:
        entity:
          domain: automation
          multiple: true
    notify_device:
      name: Notification Device
      selector:
        device:
          integration: mobile_app

trigger:
  # Trigger 1: Emergency Starts (Text Match)
  - platform: state
    entity_id: !input lockdown_trigger_entity
    to: !input lockdown_trigger_value
    id: "lockdown_start"

  # Trigger 2: Manual Recovery
  - platform: state
    entity_id: !input manual_reset_button
    id: "manual_reset"

action:
  - choose:
      # SCENARIO A: LOCKDOWN (DISABLE)
      - conditions:
          - condition: trigger
            id: "lockdown_start"
        sequence:
          # 1. Kill the Schedulers
          - service: automation.turn_off
            target:
              entity_id: !input automations_to_manage
          # 2. Notify
          - domain: mobile_app
            type: notify
            device_id: !input notify_device
            title: "⚠️ LOCKDOWN DETECTED"
            message: "Unifi reports Lockdown! Schedules have been DISABLED."

      # SCENARIO B: RECOVERY (ENABLE)
      - conditions:
          - condition: trigger
            id: "manual_reset"
        sequence:
          # 1. Revive the Schedulers
          - service: automation.turn_on
            target:
              entity_id: !input automations_to_manage
          # 2. Notify
          - domain: mobile_app
            type: notify
            device_id: !input notify_device
            title: "System Restored"
            message: "All Clear. Schedules have been RE-ENABLED."
